Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 30

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 200

#Style/GuardClause:
#  Exclude:
#    - 'rubyjack.rb'

Style/GuardClause:
  Exclude:
    - 'participant.rb'
