Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 110

Metrics/MethodLength:
  Max: 20

Metrics/ClassLength:
  Max: 200

Style/GuardClause:
  Exclude:
    - 'participant.rb'
